---
- name: configure local machine for me
  hosts: all
  become: yes

  tasks:
  
  - name: disable ubuntu apparmor
    service:
      name: apparmor
      enabled: no
      state: stopped

  - name: install apache web server
    apt:
      name:
      - apache2
      - libapache2-mod-perl2
      state: present

#  - name: download, unpack and install otobo
#    unarchive:
#      src: https://ftp.otobo.org/pub/otobo/otobo-latest-10.0.tar.gz
#      dest: /opt/otobo
#      group: www-data
#      owner: otobo
#      remote_src: yes
#      extra_opts: 
#      - --strip-components=1
#      creates: /opt/otobo/Kernel
#
  - name: checkout git repository
    git:
      repo: https://github.com/znuny/Znuny.git
      force: yes
      dest: /opt/otrs

  - name: configure otrs user
    user:
      append: yes
      comment: OTRS user
      groups: 
      - www-data 
      home: /opt/otrs
      name: otrs
      shell: /bin/bash
      state: present
      system: yes

  - name: allow su - otrs without password
    lineinfile:
      path: "/etc/sudoers"
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      state: present
      validate: /usr/sbin/visudo -cf %s

  - name: install perl modules
    apt:
      name:
      - libarchive-zip-perl 
      - libdatetime-perl 
      - libdbi-perl 
      - libmoo-perl 
      - libnet-dns-perl 
      - libtemplate-perl 
      - libtemplate-perl 
      - libxml-libxml-perl 
      - libyaml-libyaml-perl
      - libdbd-mysql-perl
      state: present

  - name: activate the default configuration file
    copy:
      src: /opt/otrs/Kernel/Config.pm.dist 
      dest: /opt/otrs/Kernel/Config.pm
      remote_src: yes

  - name: change otrs directory permissions
    file:
      path: /opt/otrs
      state: directory
      owner: otrs
      group: www-data
      recurse: yes

  - name: install perl tidy all module
    apt:
      name: libcode-tidyall-perl

  - name: activate apache modules
    shell: a2enmod perl && a2enmod deflate && a2enmod filter && a2enmod headers

  - name: configure apache for otrs
    file:
      src: /opt/otrs/scripts/apache2-httpd.include.conf
      path: /etc/apache2/sites-enabled/zzz_otrs.conf
      state: link
      remote_src: yes

  - name: whitelist otrs directory in apache configuration
    blockinfile:
      path: /etc/apache2/apache2.conf
      marker: "# {mark} OTRS APACHE WHITELIST"
      insertafter: EOF
      block: |
        <Directory /opt/otrs/>
          Options Indexes FollowSymLinks
          AllowOverride None
          Require all granted
        </Directory>

  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted

  - name: make tmp directory that Cron.sh expects
    file:
      path: /opt/otrs/var/tmp
      state: directory
      owner: otrs
      group: www-data
  
  - name: configure cron jobs for the otrs user
    shell: |
      cd /opt/otrs/var/cron/
      for foo in *.dist; do cp $foo `basename $foo .dist`; done
      cd /opt/otrs
      bin/Cron.sh start otrs

  - name: install bash auto-completion
    apt:
      name: bash-completion

  - name: fix permissions
    shell: /opt/otrs/bin/otrs.SetPermissions.pl
